"""Regenerates seed_data/demo_matches.sql from the demo database.

    python scripts/with_demo_db.py scripts/dump_seed_data.py

A data-only dump taken at the current schema head: the six sample matches,
their Impact scores and the fixed sample friend group. The player-view and
site-stats caches are left out -- they are rebuilt after loading (see
load_seed_data.py). Needs PostgreSQL 18's pg_dump (PG_DUMP overrides the path).
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

WEBAPP_ROOT = Path(__file__).resolve().parents[1]
SEED_FILE = WEBAPP_ROOT / "seed_data" / "demo_matches.sql"
PG_DUMP = os.environ.get("PG_DUMP", r"C:\Program Files\PostgreSQL\18\bin\pg_dump.exe")

# Parents first; TRUNCATE ... CASCADE clears them all regardless of order.
TABLES = ["players", "matches", "match_players", "rounds", "round_player_stats",
          "round_player_spend", "kill_events", "impact_scores", "friendships"]

HEADER = f"""-- Demo seed data for the public ValoMaths site, generated by scripts/dump_seed_data.py.
-- Data only, at the schema head; load with scripts/load_seed_data.py after `alembic upgrade head`.
-- TRUNCATE first so re-running this is idempotent.
TRUNCATE TABLE {", ".join(reversed(TABLES))} RESTART IDENTITY CASCADE;

"""

# psql meta-commands (PG18 dumps open with \\restrict) are not SQL, and
# transaction_timeout does not exist before PostgreSQL 17 (local dev runs 16).
_DROP_PREFIXES = ("\\restrict", "\\unrestrict", "SET transaction_timeout")


def main() -> None:
    url = os.environ["DATABASE_URL"].replace("postgresql+psycopg2://", "postgresql://", 1)
    command = [PG_DUMP, "--data-only", "--inserts", "--column-inserts", "--no-owner", "--no-privileges",
               *(arg for table in TABLES for arg in ("-t", f"public.{table}")), "--dbname", url]
    dump = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", check=True).stdout
    lines = [line for line in dump.splitlines() if not line.startswith(_DROP_PREFIXES)]
    SEED_FILE.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    inserts = sum(line.startswith("INSERT INTO") for line in lines)
    print(f"Wrote {SEED_FILE.name}: {inserts} rows from {len(TABLES)} tables")


if __name__ == "__main__":
    sys.exit(main())
